Celadon City Layout:
- Entered from Route 7 on the East side around (49, 11).
- The Pokémon Center is at (41, 9). It's a large building with a "POKE" sign on the roof (X=40..43, Y=8..9).
- Building at (24, 9) contains a Clefairy and an NPC.
- The main street (Y=10) has a one-way ledge directly north of it at Y=9. There is a gap in the ledge at X=20 (green grass) allowing Northward movement.
- The gap at X=20, Y=9 leads to a 2-wide alley (X=20, 21) that dead-ends at trees at Y=3. It does not connect to the northern street.
- There is NO gap between buildings at X=31. The buildings block North/South movement here.
- The main open path to the northern part of the city is located on the East side, at X=44 and X=45, just right of the Pokemon Center.
- The northernmost alley (Y=2) connects to the middle street (Y=5) ONLY at X=32.
- The middle street (Y=5) connects to the main street (Y=10) ONLY at X=45.
- The main street (Y=10, Y=11) is blocked at X=13 by the Celadon Dept. Store. The southern paths (Y=14, Y=17) dead-end at trees near X=2 and do NOT lead to Route 16.
- The correct path to Route 16 is via a paved path on the western edge of the city at Y=18. This leads directly to Route 16 at X=39.
- The Gym is definitely located in the southern area, accessible by cutting the tree at (35, 32). My previous assumption that it was on the upper path was incorrect.
- To reach the Gym, cut the tree at (35, 32), walk West along the grassy path (Y=32..34) all the way to X=5, then walk North through the gap in the ledge.
- Routing Clarification (Turn 28307): The Gym is in an enclosed area ABOVE the ledge at Y=31. However, this enclosed area cannot be reached from the main city streets because it is walled off by buildings and other ledges. The ONLY way into this enclosure is to cut the tree at (35, 32), walk West along the southern grassy path below the ledge to X=5, and then use the ramp at (5, 31) to jump UP over the ledge into the Gym enclosure. This is why the cuttable tree is required.