Fuchsia City:
- Safari Zone is located at the top center of the city. Entrance at (18, 3).
- To access the main city from the south, cut the tree at (18, 19).
- Poke Mart is at (5, 13).
- Bill's Grandpa's House is at (11, 27).
- Pokemon Center is at (19, 27).
- Fuchsia City Gym is at (5, 27).
- Voltorb encounter trap (looks like an item ball) at (25, 6) behind brown pillars.
- Good Rod: Fishing Guru's older brother is in the house at (31, 27). He offers the Good Rod. Need bag space to receive it (Discovered Turn 23068).
- Quest Hook: Safari Zone Warden lost his false teeth (mentioned by a Lass on Turn 23050).
- Safari Zone Warden's House front door is at (27, 27), back door at (22, 13) (leads to a small back room with an NPC and an item blocked by a boulder). Warden is missing his teeth and speaks gibberish. Finding them is required.
- Cuttable trees in Fuchsia City found at (18, 19), (22, 7), and (16, 11). To access Safari Zone from the south, cut the tree at (22, 7).
- WARNING: Fuchsia City is split horizontally into North and South by a wall of buildings, rocks, and ledges at Y=25. Finding the path North is my current goal.
- One-way ledge at X=23 (facing East) between Pokemon Center and Warden's House. If you jump East, you cannot walk West back.
- ROUTE (South to North): The far western edge (X=1) is a fenced-off path leading to Route 18. It does not connect to the northern half of the city. The only way to move between the North and South halves of Fuchsia City is by using CUT on the trees at (18, 19) or (22, 7).
- ROUTE (Center to Gym): Verified Turn 27868. Walk South from the Pokemon Center to Y=28, walk West along Y=28 to X=5, then walk Up to enter the Gym at (5, 27). No CUT required.