3F Layout:
- Elevator at (20, 0). Stairs UP at (26, 0) -> 4F (26, 0). Stairs DOWN at (24, 0) -> 2F (24, 0).
- Northern Corridor (Y=1..3): Runs from X=1 all the way East to the elevator/stairs area. Contains warp pad at (3, 3). Bounded on the South by a solid wall at Y=4.
- Empty Room: Spans X=1..5, Y=10..11. Accessed via locked doors at (4, 10) and (5, 10) from the Central Area. Contains NO items or warp pads.
- Gap at X=19 leads to a southern corridor. Solid wall at X=17 blocks West access from Y=6 to Y=13, EXCEPT for the shutter walls at (17, 8) and (17, 9) which can be opened with the Card Key! The southern corridor at Y=14/15 connects the East and West sides.
- Central Area: Accessed via Warp Pad at (11, 5) from 5F (3, 3).
  - Divided by a solid wall at X=10 from Y=6 downwards, AND a row of desks at Y=6 from X=11 to X=14.
  - West side (X=8/9): Contains Silph Worker at (8, 3). Path South along X=10 needs testing.
  - East side (X=11..13): Contains Scientist at (13, 9) and Warp Pad at (11, 11).
- Locked doors at (4, 10) and (5, 10) are located in the SW corner.
- Warp pad at 3F (3, 15) <-> 4F (3, 15).
- Warp pad at (23, 11) <-> 3F (27, 15) (Intra-floor warp, Verified Turn 33693). (23, 11) is blocked from the south by a row of desks at Y=13.
- NPCs: Silph worker at (20, 7), Grunt at (24, 8).
- Warp pad at (11, 11) <-> 6F (5, 3) (Verified Turn 35603). There is a yellow machine at (11, 9).
- Locked yellow doors found at (4, 10) and (5, 10). They are INACCESSIBLE from the southern corridor due to the solid wall at Y=13. They must be accessed from within the central area.
- 3F Central Area West Side path: From X=9, Y=4, path goes South to Y=12, then West to X=6, then North to access the locked doors at (4, 10) and (5, 10).