9F Layout:
- Elevator at (12, 0). Stairs UP to 10F at (10, 0). Stairs DOWN to 8F at (8, 0).
- Defeated Grunt at (10, 2) permanently blocks the path south along X=10.
- Desks at Y=4 block path south along X=11..13.
- The Central Room is totally isolated from the Elevator area. It can only be accessed via the warp pad at (9, 11) from 4F (11, 7).
- Western Corridors:
  - Corridor at X=1 runs from Y=1 to Y=7.
  - Corridor at X=6 runs from Y=1 to Y=7.
  - Horizontal corridor at Y=7 connects X=1 to X=6.
  - Vertical corridor at X=3 connects Y=7 to Y=9.
  - Horizontal corridor at Y=9 connects X=1 to X=6. Locked yellow doors at (10, 8) and (11, 8).
  - Corridor at X=1 runs from Y=10 to Y=16.
  - Corridor at X=6 runs from Y=9 to Y=16.
  - Defeated Grunt at (1, 9) blocks movement along X=1.
  - Horizontal corridor at Y=16 connects X=1 to X=6. No items or warps in this entire southwest block.
- Eastern side of northern corridor ends at a wall at X=15. No paths south.
- 9F open areas are fully explored.
- Warp pad at (13, 7) <-> 10F (17, 11). (17, 11) is in an isolated room containing beds.
- Locked yellow doors at (10, 8) and (11, 8).
- Central Room (South of doors at Y=8): Bounded by walls at X=7 and X=15. Block of desks from (10, 12) to (11, 14) and (12, 10) to (13, 12). Contains pacing Grunts and Warp Pads at (13, 15) and (9, 11). (Accessed by opening door at 10, 8).