7F Layout (Verified):
- Elevator at (18, 0). Stairs UP at (16, 0), DOWN at (14, 0).
- Northern corridor runs East-West.
- Vertical corridor at X=14 is blocked by NPC at (14, 5).
- Vertical corridor at X=16 runs from Y=1 to Y=15, bounded by walls at X=15 and X=17. Connects to South-East area.
- South-East Area: Contains Grunt at (19, 14) and Warp Pad at (21, 15).
- Central Area North (X=7..12, Y=2..13): Contains Worker at (10, 2), Grunt at (11, 4), Warp Pad at (11, 5), Warp Pad at (11, 9). A short partition wall at Y=7 (X=10..12) requires walking around via X=9 to travel between the top and bottom halves. Bounded North by desks at Y=1, East by wall at X=13, and South by desks at Y=13. Completely enclosed. Accessible ONLY via the Warp Pad at (11, 5) from 2F (27, 15).
- Isolated West Room (X=1..6, Y=1..12): Accessible ONLY via Warp Pad at (3, 11) which connects to 7F (11, 9). Blocked from the south by a solid wall at Y=13. Contains defeated Grunt at (3, 8) and an NPC (Silph Worker) at (4, 2). Path North is at X=1.
- Warp Pads:
  - (11, 9) <-> 7F (3, 11)
  - (21, 15) <-> 5F (27, 3)