Vermilion City Layout:
- Vermilion Gym: Entrance is around (12, 19). The path to it is blocked by cuttable trees at (14, 18) and (15, 18).
- Ocean/Water: Present in the southeast area of the city.
- Trade House: Located at (15, 13). A girl inside trades her Farfetch'd for a Spearow.
- Pokémon Fan Club: Located at (9, 13). Contains the Fan Club Chairman who gives the Bike Voucher.
- West Boundary: Water edge located at X=7, preventing further westward movement from the main city paths.
- Poké Mart: Located at (23, 13).
- Pokémon Center: Located at (11, 3).
- Southeast House: Located at (23, 19).
- East Area: Accessed via Y=8. Dead ends in the Southeast at a house (23, 19). Bordered by water to the East (X=26) and South (Y=22).
- East Exit: Route 11 is accessed by walking East EXACTLY at Y=14. The main vertical path at X=18 intersects Y=14. Do NOT attempt to go East at Y=8 or Y=12, as these lead to dead ends blocked by a horizontal line of trees at Y=13. Map coordinates transition at X=39, Y=14.
- Navigation: The main vertical path connecting the southern half of the city to the northern half (Pokémon Center) is located at X=18.
- S.S. Anne Pier: NOT at X=20/21. The path at X=20/21 dead-ends at water at Y=22.
- S.S. Anne Pier Discovery: The entrance to the pier is accessed by walking to the far East side of Vermilion City (X=30, Y=14), heading South onto the wooden dock down to Y=27, then West along the dock to X=18, and finally South to the Sailor at (19, 30). The Sailor checks the ticket and says 'Welcome', but does not move; bypass him by walking South on the left side of the pier at X=18.