Victory Road 1F:
- EXIT: (8,17) is an exit warp to Route 23.
- LADDERS:
  - (1,1): True Entrance to 2F West. Reached via the West path (X=1/X=2) by pushing the boulder at (2,10).
  - (25,14): Inaccessible from the South entrance due to solid boundaries blocking the East path.
- ELEVATION & BOUNDARY MODEL:
  - Level 1 (Low): Dark Red blocky floors.
  - Level 3 (High): Dark Purple speckled floors.
  - Level 3 extends East to at least (17,11) (visited Turn 61706). Obstacles around X=8 must be bypassed.
- STAIRS:
  - (5,13): Connects Level 1 (Y=14) UP to Level 3 (Y=12).
  - (7,7): Connects Level 3 (Y=8) DOWN to Level 1 North (Y=6).